name: manajemen_kost_by_user
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_storage: ^11.2.4
  firebase_messaging: ^14.6.4
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  image_picker: ^1.0.0
  mask_text_input_formatter: ^2.4.0
  octo_image: ^1.0.2
  shared_preferences: ^2.2.0
  url_launcher: 6.0.20
  intl: ^0.18.1
  blurhash_dart: ^1.2.1
  image: ^4.0.17
  grouped_list: ^5.1.2

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

